[platformio]
name = "Molonary1D hardware code"
framework = Arduino

[env]
board = mkrwan1310
platform = atmelsam
build_type = debug
lib_deps =
  ; name-based (built-in library in framework)
  SPI
  Arduino_Low_Power
  SD
  LoRa
  RTCLib
  MKRWAN
  Queue
  RTCZero
  FlashStorage

lib_dir = ./field_code/libs


[env:test_Relay_Lora]
build_type = debug
src_dir = ./tests/Relay_Lora

[env:test_Sensor_Lora]
build_type = debug
src_dir = ./tests/Sensor_Lora

